branches:
  only:
    - "master"

language: node_js
node_js:
  - 16

install: 
  - npm install -g serverless
  - npm install
before_script: 
  - chmod +x aws_credential.sh
script: 
  - ./aws_credential.sh
  - npm run build
  - npm run deploy
 